
export const patientData = [
    {
      firstName: "Harm",
      lastName: "van der Pol",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"805a6eb8-e244-46cc-af4b-3a417815388c",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Sander",
      lastName: "van Wijk",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"0f40d813-2819-4c73-b5ba-a1da6bf42cb3",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Diewertje",
      lastName: "van Loon",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"e0ff1bfb-dde8-4b40-a2f7-90b769600e2a",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Arjan",
      lastName: "van Vliet",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"af4895cb-4d1c-47c3-87f4-d2fdba2ace25",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Eelco",
      lastName: "van der Meer",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"10fa1020-1a70-45aa-871f-21a2f094c19f",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Willemijn",
      lastName: "Hofman",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"b3794e78-de26-4ca0-bb28-14c6bbb67f9c",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Reinout",
      lastName: "van der Veen",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"cf1c098f-ddf3-4607-8b14-e18b1c0ccaf8",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Willemijn",
      lastName: "van Dijk",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"a1626b81-5de0-4047-b1fb-7e73bc3b904a",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Boudewijn",
      lastName: "van Dijk",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"b483d16a-82ea-44cf-a37c-0390d0b689a9",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Doortje",
      lastName: "de Bruijn",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"4e2c8719-a989-40cb-8661-d94bad62eeba",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Reinout",
      lastName: "Hoekstra",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"628fd5b3-47a4-4032-a8a7-940efbf03a84",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Victor",
      lastName: "de Graaf",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"6fe420bc-0642-4424-ba02-091612ee2198",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Kristien",
      lastName: "Scholten",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"46a942a3-1709-483e-a2f7-ddf986da8e09",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Anna",
      lastName: "Hendriks",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"09a4965b-68be-46cb-8ede-6b3b83b4656b",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Gerrit",
      lastName: "Hoekstra",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"f5ef71c9-952f-4e83-830e-9b2996855c84",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Femke",
      lastName: "de Graaf",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"8936407a-55de-4a5b-992d-d28486d24824",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Tineke",
      lastName: "Scholten",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"0e26dc91-3d84-473a-9032-616245783471",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Arjan",
      lastName: "Verhoeven",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"99f734be-7e54-4727-a7da-f5d0f50d0b30",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Willeke",
      lastName: "Kuijpers",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"177e910c-5b60-4ecf-953e-47b6bc39701c",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Suzanne",
      lastName: "Smeets",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"e67b5db7-9eab-423c-99e3-2970c730cfd2",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Maaike",
      lastName: "Koster",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"68117371-07d8-4767-91ae-9476494dbb3f",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Quintin",
      lastName: "Kuijpers",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"9f37d57c-22bd-4821-b37f-a1ef35ea3757",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Lonneke",
      lastName: "Evers",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"bc58ad26-bdce-4671-8c6d-b4da30b533aa",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Hendrika",
      lastName: "Jacobs",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"b9f4d5d0-01bc-4241-930c-b2b55ad6b3ca",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Willemijn",
      lastName: "Smit",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"e694482e-de16-461a-be28-74e0a9d330e0",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Corien",
      lastName: "Dekker",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"0bce250d-11d7-4bbe-ad4f-7d96d3a37c06",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Mirthe",
      lastName: "Timmermans",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"50c732b6-f01c-40c0-8ac8-d2a9dbf16ecc",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Christiaan",
      lastName: "Bakker",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"d7fb02aa-276f-4041-840d-e392cf9d2ace",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Laura",
      lastName: "Kuijpers",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"dfc50bd5-2325-4b13-92fb-829b6f682568",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Tineke",
      lastName: "Timmermans",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"474d0018-105d-46cb-8296-c07f00e8135f",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Roos",
      lastName: "Hendriks",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"708b34b9-a5e8-41bd-9cda-f1dce4eb3e01",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Emiel",
      lastName: "Vermeulen",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"9c34a91a-e010-4237-bdf9-efa619749464",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Paulien",
      lastName: "Hoekstra",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"53e23c92-d9b7-4287-924e-88329471100f",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Lotte",
      lastName: "Timmermans",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"dbb7413c-085d-43b1-94c4-474b7c113c4d",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Christien",
      lastName: "Vos",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"d80e9089-c6e2-472f-b63b-e07cc4822e98",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Johanneke",
      lastName: "Bakker",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"adcadb67-4891-4e3d-8db2-b0fc4fdf3281",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Paulien",
      lastName: "Hendriks",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"34810c1e-068d-4810-946d-41208e82c435",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Lieke",
      lastName: "Hermans",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"54e26a5c-cc77-425a-ac2d-755ee873cb55",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Eefke",
      lastName: "Vermeulen",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"e8685c1b-5f1a-45a2-ad08-b38dc05cfebe",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Emma",
      lastName: "Gerritsen",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"8aef84d1-92e5-4e0b-8d9d-38bf56c9f6cb",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Thomas",
      lastName: "Vermeulen",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"126a8957-1288-42fb-90a4-2dcb8343ff39",
      gender: "male",
      region: "Netherlands",
    },
    {
      firstName: "Suzanne",
      lastName: "Bakker",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"ee4c2e5b-f47c-4668-b1ac-2d9ec1fd0a99",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Hanneke",
      lastName: "Wolters",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"d81fe0ad-6733-421c-a663-a59dd9947548",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Christien",
      lastName: "Mulder",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"5619ff4b-e4e6-4e18-880b-7c86c443b645",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Mirthe",
      lastName: "Kuiper",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"77dc4832-56c9-4345-a982-6214c20a8d5a",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Neeltje",
      lastName: "Schouten",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"6aaab366-b4e6-4970-9d01-957664e45b9a",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Tineke",
      lastName: "Kuijpers",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"f7857e13-960d-4208-8dd1-37126efb5ce4",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Thea",
      lastName: "Hoekstra",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"c9390bcd-5f33-4df3-bc7c-7afdb2f3bc40",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Nelleke",
      lastName: "Molenaar",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"51008864-93ec-42b8-9f4c-0197b8cb6fb4",
      gender: "female",
      region: "Netherlands",
    },
    {
      firstName: "Leentje",
      lastName: "Wolters",
      phoneNr:"",
      eMail:"",
      isSick:false,
      id:"1f55999b-5eac-4025-98ea-2ee75d3133a2",
      gender: "female",
      region: "Netherlands",
    },
  ];