export const patientData = [
    {
      name: "Harm van der",
      surname: "Pol",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Sander van",
      surname: "Wijk",
      gender: "male",
      region: "Netherlands",
    },{
      name: "Diewertje van",
      surname: "Loon",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Arjan van",
      surname: "Vliet",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Eelco van der",
      surname: "Meer",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Willemijn",
      surname: "Hofman",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Reinout van der",
      surname: "Veen",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Willemijn van",
      surname: "Dijk",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Boudewijn van",
      surname: "Dijk",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Doortje de",
      surname: "Bruijn",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Reinout",
      surname: "Hoekstra",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Victor de",
      surname: "Graaf",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Kristien",
      surname: "Scholten",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Anna",
      surname: "Hendriks",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Gerrit",
      surname: "Hoekstra",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Femke de",
      surname: "Graaf",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Tineke",
      surname: "Scholten",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Arjan",
      surname: "Verhoeven",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Willeke",
      surname: "Kuijpers",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Suzanne",
      surname: "Smeets",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Maaike",
      surname: "Koster",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Quintin",
      surname: "Kuijpers",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Lonneke",
      surname: "Evers",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Hendrika",
      surname: "Jacobs",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Willemijn",
      surname: "Smit",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Corien",
      surname: "Dekker",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Mirthe",
      surname: "Timmermans",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Christiaan",
      surname: "Bakker",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Laura",
      surname: "Kuijpers",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Tineke",
      surname: "Timmermans",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Roos",
      surname: "Hendriks",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Emiel",
      surname: "Vermeulen",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Paulien",
      surname: "Hoekstra",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Lotte",
      surname: "Timmermans",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Christien",
      surname: "Vos",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Johanneke",
      surname: "Bakker",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Paulien",
      surname: "Hendriks",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Lieke",
      surname: "Hermans",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Eefke",
      surname: "Vermeulen",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Emma",
      surname: "Gerritsen",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Thomas",
      surname: "Vermeulen",
      gender: "male",
      region: "Netherlands",
    },
    {
      name: "Suzanne",
      surname: "Bakker",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Hanneke",
      surname: "Wolters",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Christien",
      surname: "Mulder",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Mirthe",
      surname: "Kuiper",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Neeltje",
      surname: "Schouten",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Tineke",
      surname: "Kuijpers",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Thea",
      surname: "Hoekstra",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Nelleke",
      surname: "Molenaar",
      gender: "female",
      region: "Netherlands",
    },
    {
      name: "Leentje",
      surname: "Wolters",
      gender: "female",
      region: "Netherlands",
    },
  ];